version: '3'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 80:80

  service1:
    build:
      context: app
      dockerfile: Dockerfile
    depends_on:
    - nginx
    expose:
    - 8080